### PR TITLE
Play track and next, previous, pause, resume a track

### PR DESCRIPTION
**Pull request by vu9596**
Play track and next, previous, pause, resume a track. Display mini player
https://edu-redmine.framgia.vn/issues/2593

### CODE REVIEW

**Comment by vu9596** [comment]
ready

**Comment by vu9596** [comment]
ready

**Comment by vu9596** [comment]
ready

**Review by NguyenMinhTuanB — APPROVED** [review]

**Comment by NguyenMinhTuanB** [comment]
merged

**Pull request merged**
