### PR TITLE
Create base packages

### PR DESCRIPTION
**Pull request by chicky-dev**
Create base packages following MVP pattern
https://edu-redmine.framgia.vn/issues/2587

### CODE REVIEW

**Comment by VoLy** [comment]
ready

**Comment by chicky-dev** [comment]
ready

**Comment by chicky-dev** [comment]
ready

**Comment by chicky-dev** [comment]
ready

**Review by NguyenMinhTuanB — APPROVED** [review]

**Comment by NguyenMinhTuanB** [comment]
merged

**Pull request merged**
